### ISSUE TITLE
Implement library for CAPE sandbox

### ISSUE THREAD

**Issue by deadbits** [InQuest/sandboxapi#7]
It’s a fork of Cuckoo (I believe) that can take files, URLs, or PCAPs. I imagine the endpoints are very similar to Cuckoo  
API Docs: https://cape.contextis.com/api/

**Comment by cmmorrow** [comment]
I'm currently working on v1.5 and v2.0, with 2.0 including several new features. I'll try to add this sandbox in v2.1.
